"""empty message

Revision ID: a0105a9f0765
Revises: 3b9dd2737c51
Create Date: 2024-09-01 12:42:29.978387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0105a9f0765'
down_revision = '3b9dd2737c51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mailing_list_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('polls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('poll_paintings',
    sa.Column('poll_id', sa.Integer(), nullable=False),
    sa.Column('painting_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['painting_id'], ['paintings.id'], name=op.f('fk_poll_paintings_painting_id_paintings')),
    sa.ForeignKeyConstraint(['poll_id'], ['polls.id'], name=op.f('fk_poll_paintings_poll_id_polls')),
    sa.PrimaryKeyConstraint('poll_id', 'painting_id')
    )
    op.create_table('votes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('painting_id', sa.Integer(), nullable=False),
    sa.Column('poll_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['painting_id'], ['paintings.id'], name=op.f('fk_votes_painting_id_paintings')),
    sa.ForeignKeyConstraint(['poll_id'], ['polls.id'], name=op.f('fk_votes_poll_id_polls')),
    sa.ForeignKeyConstraint(['user_id'], ['mailing_list_entries.id'], name=op.f('fk_votes_user_id_mailing_list_entries')),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('ix_users_username')
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.create_index('ix_users_username', ['username'], unique=True)

    op.drop_table('votes')
    op.drop_table('poll_paintings')
    op.drop_table('polls')
    op.drop_table('mailing_list_entries')
    # ### end Alembic commands ###
