"""empty message

Revision ID: a4307628993e
Revises: b929e394b6c1
Create Date: 2024-07-19 23:51:43.122821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4307628993e'
down_revision = 'b929e394b6c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('folders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('paintings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('folder_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_paintings_folder_id_folders'), 'folders', ['folder_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('ix_users_username')
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.create_index('ix_users_username', ['username'], unique=True)

    with op.batch_alter_table('paintings', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_paintings_folder_id_folders'), type_='foreignkey')
        batch_op.drop_column('folder_id')

    op.drop_table('folders')
    # ### end Alembic commands ###
